# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DisneyTest1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DisneyTest1
    pod 'Alamofire'
    pod 'SDWebImage'
  target 'DisneyTest1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DisneyTest1UITests' do
    # Pods for testing
  end

end
